name: Daily Report

on:
  schedule:
    # 04:37 UTC — це 06:37 за Києвом (менше черг на сервері)
    - cron: '37 4 * * *'
    # 12:12 UTC — це 14:12 за Києвом
    - cron: '12 12 * * *'
  push:
    branches: [ main ] # Кожен твій пуш тепер теж запускає бота
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Telegram Bot Script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          MY_CHAT_ID: ${{ secrets.MY_CHAT_ID }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: python main.py
