name: Daily Channel Content

on:
  workflow_dispatch:      # Дозволяє запускати бота вручну кнопкою
  repository_dispatch:    # Дозволяє сервісу cron-job.org запускати бота
    types: [run_bot]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        # Встановлюємо бібліотеки для запитів та для роботи з київським часом
        run: pip install requests pytz

      - name: Run logic
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
